name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.template"
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - run: npm test
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
